root: true
plugins:
  - react
  - prettier
extends:
  - plugin:prettier/recommended
  - plugin:react/recommended
parser: babel-eslint
env:
  browser: true
  es6: true
globals:
  "$": true
  __DEV__: true
  inkdrop: true
  _REACT_EXTENSION_PATH: true
  BROWSER: true
  fetch: true
  URL: true
  Image: true
  btoa: true
  alert: true
rules:
  no-useless-escape: 0
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: true
      semi: false
  prefer-const: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
